spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${vcap.services.postgresql.credentials.hostname}:${vcap.services.postgresql.credentials.port}/${vcap.services.postgresql.credentials.dbname}
    username: ${vcap.services.postgresql.credentials.username}
    password: ${vcap.services.postgresql.credentials.password}